# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12f4fb55feed9ae434f4f8747c1684ef41052ca807d30170a9c0b200c979a1b04f5e4b060e3e77e929d1c901a908c84e046e7ec30b2302371380f21d2184e21c

test:
  secret_key_base: 8400a4655097238f73787c5532b30746257a73105470960826f222657f0544e36778c1c33bc6be10dbe608f8a315f551841e3c83f2943bd986a45fad2b7ecb61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
